version: '3.7'

services:
  ffc-ce-web:
    build: .
    image: ffc-ce-web
    command: npm run start:watch
    environment:
      PAYMENT_URL: http://ffc-ce-payment-orchestrator:3002
      COOKIE_PASSWORD: aPasswordNotUsedAnywhereOnlyLocallyWhenTesting
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
