version: '3.7'

services:
  ffc-ce-web:
    build: .
    image: ffc-ce-web
    command: npm run start:watch
    environment:
      PAYMENT_URL: http://ffc-ce-payment-orchestrator:3002
      COOKIE_PASSWORD: aPasswordNotUsedAnywhereOnlyLocallyWhenTesting
      PAYMENT_CALCULATION_URL: http://ffc-ce-payment-orchestrator:3002/payment-calculation
    volumes:
      - ./server/:/usr/src/app/server/
      - ./index.js:/usr/src/app/index.js
      - ./package.json:/usr/src/app/package.json
