#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

# Set Docker/Kubernetes resource names managed by this script
basicAuthSecret="ffc-ce-basic-auth"
containerName="ffc-ce-web"
dockerPrefix="ffc-ce-web"

(
  cd "${projectRoot}"

  helm delete --purge \
    ${containerName}
)
