#!/bin/bash

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"

  docker-compose down -v
  docker-compose build --no-cache
  docker-compose up --force-recreate
)
