#!/bin/bash
docker-compose -f docker-compose.yaml -f docker-compose.test.yaml down -v
docker-compose -f docker-compose.yaml -f docker-compose.test.yaml build --no-cache
docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --force-recreate  --exit-code-from ffc-ce-web
