#!/bin/bash
docker-compose -f docker-compose.yaml -f docker-compose.test.yaml down -v
docker-compose -f docker-compose.yaml -f docker-compose.test.yaml build
docker-compose -f docker-compose.yaml -f docker-compose.test.yaml run ffc-ce-web
