environment: development
image: ffc-ce-web
namespace: ffc-ce
name: ffc-ce-web
workstream: ffc-ce

labels:
  component: web

service:
  port: 80
  type: ClusterIP

secret:
  name: ffc-demo-basic-auth
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 80Mi
  limitCpu: 80m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restClientTimeoutMillis: 20000
  staticCacheTimeoutMillis: 54000
  port: 3000
  cookiePassword: passwordpasswordpasswordpasswordpassword
  paymentUrl: http://ffc-ce-payment-orchestrator.ffc-ce
  paymentCalculationUrl: http://ffc-ce-payment-orchestrator.ffc-ce/payment-calculation

ingress:
  class: nginx
  endpoint: ffc-ce

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
