environment: development
image: ffc-ce-web
name: ffc-ce-web
auth:
imagePullSecret:

deployment:

service:
  port: 80
  type: ClusterIP

container:
  imagePullPolicy: IfNotPresent
  redeployOnChange: update this field to force a change
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 80Mi
  limitCpu: 80m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restartPolicy: Always
  paymentUrl: http://ffc-ce-payment-orchestrator.ffc-ce
  paymentCalculationUrl: http://ffc-ce-payment-orchestrator.ffc-ce/payment-calculation
  cookiePassword: H3QrRq0AhhsXLI6cSEbvTHUoa2C3qOybLpO1ku48
  restClientTimeoutMillis: 20000
  staticCacheTimeoutMillis: 54000
ingress:
  endPoint: ffc-ce
  server: acme-corp.com
replicas: 1
minReadySeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
